### ISSUE TITLE
How to convert custom types? 

### ISSUE THREAD

**Issue by g10z3r** [neo4j-labs/neo4rs#15]
How to convert custom types so that they can be specified in the function `param`?

**Comment by declark1** [comment]
This is an issue and may prevent me from using this crate unfortunately. The types module is private so conversions cannot even be implemented.

**Comment by 0xDjole** [comment]
@declark1 This looks good?  https://github.com/neo4j-labs/neo4rs/pull/69

**Comment by knutwalker** [comment]
`0.7.0-rc.2` now pub exports the BoltType(s), we also added extensive serde support for converting results into custom types. At some point, we will also use serde for query params.
