### ISSUE TITLE
Neo4rs 5.x compatibility

### ISSUE THREAD

**Issue by Reichenbachian** [neo4j-labs/neo4rs#170]
Hey all! In the docs, it says that neo4rs supports 4.x specifications. Are there plans to start supporting 5.x anytime soon? We'd love to use some of the new embedding support from neo4j.

**Comment by knutwalker** [comment]
Hey,

it's true that only versions 4.0 and 4.1 are supported, but this refers to the Bolt protocol version, which is the same as the Neo4j versions. Newer Neo4j versions are usually able to speak to a driver using an older Bolt protocol and the current versions all still speak at least Bolt 4.0.

Here is the compatibility table: https://neo4j.com/docs/bolt/current/bolt-compatibility/

Support for protocol versions 4.0 and 4.1 will eventually be removed. Support for newer bolt protocol versions in this driver is also planned, but it's still gonna be a while.

**Comment by Reichenbachian** [comment]
Appreciate the quick and detailed response!
