### ISSUE TITLE
Make types public to support conversion implementations

### ISSUE THREAD

**Issue by declark1** [neo4j-labs/neo4rs#18]
Conversions to/from BoltType is not possible as the module and types are private. This is a major deal breaker for using this crate.

Query params can only be built using existing supported types.

**Comment by tobias-z** [comment]
I would love this. Currently it does not seem possible to use `BoltType` with generics.
I would love to be able to do something like this:

```rust
async fn get_single<T>(result: Result<RowStream, Error>, key: &str) -> Result<T, Error>
where
    T: std::convert::TryFrom<neo4rs::types::BoltType>,
{
    match result {
        Ok(mut stream) => match stream.next().await {
            Ok(Some(row)) => Ok(row.get(key).unwrap()),
            Ok(None) => Err(neo4rs::Error::UnknownMessage("unknown error".to_string())),
            Err(e) => Err(e),
        },
        Err(e) => Err(e),
    }
}
```

**Comment by knutwalker** [comment]
`0.7.0-rc.2` now pub exports the BoltType(s)
