### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by SolidTux** [neo4j-labs/neo4rs#19]
It looks like this repository is abandoned, but quite some people seem to be happy to provide pull requests and have forks.

Would you be happy to transfer ownership of the crate to someone in case you don't plan to continue working on it?

**Comment by yehohanan7** [comment]
Sorry Guys, I was not able to actively maintain this project. I handed over the ownership to Neo4j, you can expect new versions going forward!

Thanks,
John

**Comment by jexp** [comment]
Yes, thank you @yehohanan7 so much for all your work.
We want to revive this rust driver for Neo4j which is already really awesome and have a list of improvements that we'll turn into GitHub issues.

We have a number of engineers that are interested in contributing as part of the Neo4j Labs efforts, but of course would love to see contributions from the Rust community.

Looking forward to seeing improvements and releases coming in soon.

@SolidTux thanks for raising this issue.
