### ISSUE TITLE
Add serde support

### ISSUE THREAD

**Issue by knutwalker** [neo4j-labs/neo4rs#33]
Implement de/serializing bolt results to user types. Users can use their Serialize/Deserialize types to send/receive data without having to go bolt -> rust -> user

**Comment by puzza007** [comment]
I implemented a quick and dirty branch of serialization here https://github.com/puzza007/neo4rs/tree/serde-serialize. Only lightly tested so far.

**Comment by 0xDjole** [comment]
will this be merged?

**Comment by EtienneProthon** [comment]
Hello there, seems some people worked on that and we have PR #69 (thx @0xDjole ), i am very interested by this feature so i would like to know when it will be merged. 
If you need help with this project I am available !

**Comment by knutwalker** [comment]
In `0.7.0-rc.2` we are adding a bolt dataformat implementation so we can support various serde conversion methods on the public types.
