### ISSUE TITLE
Latest tagged version is from 2021, newest crate available from crates.io is 0.5.9

### ISSUE THREAD

**Issue by daveman1010221** [neo4j-labs/neo4rs#73]
Hey, all. I apologize if this is the wrong place for this.

It took a while to confirm, but I was having problems with the driver establishing connection with a recent 5.4.0 server. When I realized the newest available crate on crates.io might be rather old, I built this from source and tested it. It works.

Does anyone know who updates the tagged releases here? Anyone know who updates crates.io? I'm willing to help out, but I'm not entirely sure where to start. Is there any official build instructions? My local build is a bit of a mess at the moment. Using a locally-built crate to resolve issues is not ideal. Thanks.

**Comment by knutwalker** [comment]
Hi @daveman1010221,

We've moved this project to the neo4j-labs organization recently and proper support for Neo4j 5 has only been added recently. We are currently preparing a first release to crates.io from the new organization, soon.
