### ISSUE TITLE
update from 0.6.0 to 0.6.1 get empty host error

### ISSUE THREAD

**Issue by DualHappiness** [neo4j-labs/neo4rs#93]
I use this lib in k8s with headless service like `neo4j-headless`

And when I upgrade to 0.6.1, I get error
```
Invalid URI: empty host
```

```rust
// Init neo4j
// this uri will be `neo4j-headless:7687`
let uri = format!("{}:{}", opt.neo4j_host, opt.neo4j_port);
let graph = Neo4jGraph::new(&uri, &opt.neo4j_user, &opt.neo4j_pass).await?;
```

**Comment by s1ck** [comment]
Hey @DualHappiness 

You are missing the URI scheme: you need to prefix your `uri` with `bolt://`, i.e. `bolt://neo4j-headless:7687`.

Let me know if it works for you :)

**Comment by DualHappiness** [comment]
> Hey @DualHappiness
> 
> You are missing the URI scheme: you need to prefix your `uri` with `bolt://`, i.e. `bolt://neo4j-headless:7687`.
> 
> Let me know if it works for you :)
> 
> edit: it seems we had some code in place that automatically prefixes with `bolt` if the scheme is missing. And this should still work. So it's actually I bug and we'll look into it. Thx.

Yes, it works.
